### ISSUE TITLE
[vue] Error: Cannot find module 'virtual:pwa-register'

### ISSUE THREAD

**Issue by viniciusknob** [vite-pwa/vite-plugin-pwa#395]
I'd like to update the sw using the prompt for update. The code below doesn't work well, because it is necessary to configure the typescript, but I don't use typescript, so how can I use the `virtual:pwa-register` properly?

I saw the FAQ in https://vite-pwa-org.netlify.app/guide/faq.html, but it is talking about typescript configuration again.

Maybe I'm losing a small thing, but I'm no so sure what.

vite.config.js
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { VitePWA } from "vite-plugin-pwa";

const path = require("path");
export default defineConfig({
  plugins: [
    vue(),
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: [
        "favicon.ico",
        "logo.png",
        "assets/icons/apple-touch-icon.png",
        "assets/icons/safari-pinned-tab.svg",
        "assets/icons/material/*",
        "assets/materialize/*",
      ],
      manifest: {
        id: "sample.app",
        name: "Sample App",
        short_name: "SampleApp",
        start_url: `/?v=${new Date().toISOString()}`,
        description: "sample description app",
        theme_color: "#3e4095",
        background_color: "#3e4095",
        icons: [
          {
            src: "assets/icons/192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "assets/icons/512.png",
            sizes: "512x512",
            type: "image/png",
          },
          {
            src: "assets/icons/512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "assets/icons/512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        screenshots: [
          {
            src: "assets/icons/512.png",
            type: "image/png",
            sizes: "512x512",
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
```

helpers/pwa/vite-plugin-pwa.js
```js
import { useRegisterSW } from "virtual:pwa-register/vue";

/**
 * Periodic Service Worker Updates
 * https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html
 * https://vite-pwa-org.netlify.app/frameworks/vue.html
 */
class VitePluginPWA {
  static periodicUpdate() {
    const intervalMS = 60 * 60 * 1000;
    return useRegisterSW({
      onRegisteredSW(swUrl, r) {
        r &&
          setInterval(async () => {
            if (!(!r.installing && navigator)) return;
  
            if ("connection" in navigator && !navigator.onLine) return;
  
            const resp = await fetch(swUrl, {
              cache: "no-store",
              "cache-control": "no-cache",
            });
  
            if (resp?.status === 200) await r.update();
          }, intervalMS);
      },
    });
  }
}
```

main.js
```js
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import VitePluginPWA from "./helpers/pwa/vite-plugin-pwa";

VitePluginPWA.periodicSwUpdate();

createApp(App).use(router).mount("#app");
```

Stacktrace:
```bash
app.sample.com.br on  main [!?] via  v16.15.1 
❯ npm run app:preview

> app.sample.com.br@0.1.0 app:preview
> vercel --local-config vercel.preview.json dev

Vercel CLI 28.4.8
> Running Dev Command “vite build & vite preview --port $PORT”
failed to load config from C:\projetos\sample\app.sample.com.br\vite.config.js
error during build:
Error: Cannot find module 'virtual:pwa-register'
Require stack:
- C:\projetos\sample\app.sample.com.br\vite.config.js
- C:\projetos\sample\app.sample.com.br\node_modules\vite\dist\node\chunks\dep-db16f19c.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\projetos\sample\app.sample.com.br\vite.config.js:36:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/projetos/sample/app.sample.com.br/node_modules/vite/dist/node/chunks/dep-db16f19c.js:63524:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
failed to load config from C:\projetos\sample\app.sample.com.br\vite.config.js
error when starting preview server:
Error: Cannot find module 'virtual:pwa-register'
Require stack:
- C:\projetos\sample\app.sample.com.br\vite.config.js
- C:\projetos\sample\app.sample.com.br\node_modules\vite\dist\node\chunks\dep-db16f19c.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\projetos\sample\app.sample.com.br\vite.config.js:36:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/projetos/sample/app.sample.com.br/node_modules/vite/dist/node/chunks/dep-db16f19c.js:63524:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[...]
```

**Comment by viniciusknob** [comment]
> @viniciusknob Why are you loading `VitePWA` plugin using the virtual module on your vite config file? https://vite-pwa-org.netlify.app/guide/#configuring-vite-plugin-pwa

Hi @userquin , I'm not using VitePWA on vite config file. The config is in another file, isolated, and called in main.js (I updated my first comment with this info).

**Comment by userquin** [comment]
@viniciusknob you need to configure the pwa plugin in your vite config file `C:\projetos\sample\app.sample.com.br\vite.config.js`: if the pwa plugin is not configured importing any pwa virtual module will fail, check my previous link

**Comment by userquin** [comment]
@viniciusknob that's weird, can you share a minimal repro? the build is working on your local?

**Comment by viniciusknob** [comment]
@userquin you are right! The problem is in the server startup, so I decided to use dynamic import, following this document: https://vite-pwa-org.netlify.app/guide/faq.html#vite-pwa-virtual-module. Problem solved! Thank you for your help.
