### ISSUE TITLE
Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by piotr-cz** [vite-pwa/vite-plugin-pwa#405]
After updating to v0.13.2 this errors stops the build (`tsc && vite build`):

```
error during build:
Error: Dynamic require of "path" is not supported
    at file:///xxxx/node_modules/vite-plugin-pwa/dist/chunk-22M6QDW2.mjs:12:9
    at node_modules/.pnpm/picomatch@2.3.1/node_modules/picomatch/lib/picomatch.js (file:///xxx/node_modules/vite-plugin-pwa/dist/rollup-plugin-replace.es-E5RG33HN.mjs:1316:16)
    at __require2 (file:///xxx/node_modules/vite-plugin-pwa/dist/chunk-22M6QDW2.mjs:15:50)
    at node_modules/.pnpm/picomatch@2.3.1/node_modules/picomatch/index.js (file:///xxx/node_modules/vite-plugin-pwa/dist/rollup-plugin-replace.es-E5RG33HN.mjs:1460:22)
...
```

When I change "type"="module" to "commonjs" in package.json, error goes away

Related vite issues I found:
- https://github.com/evanw/esbuild/issues/1921
- https://github.com/Subwaytime/vite-aliases/issues/33

**Comment by thovden** [comment]
Also got this wotn 0.13.2 while building with vite. 0.13.1 works fine.

**Comment by laurentpayot** [comment]
Same here. I had to revert to 0.13.1.

**Comment by sharmapukar217** [comment]
> Same here. I had to revert to 0.13.1.

I am having same issue even with 0.13.1

**Comment by userquin** [comment]
shoud be fixed with `v0.13.3`

**Comment by piotr-cz** [comment]
Thanks!
update to 0.13.3 fixed the problem for me
