### ISSUE TITLE
SvelteKit: docker build or preview fail as assect  

### ISSUE THREAD

**Issue by xmlking** [vite-pwa/vite-plugin-pwa#437]
After the build, when we run  preview i.e., `pnpm preview`:
 which activates service worker,  script URLs change from full URL `http://localhost:4173/auth/_app/immutable/assets/_layout-e564fd4d.css"   to relative  `./_app/immutable/assets/_layout-e564fd4d.css` 

This causes the URL fetch to fail as the asset base path is wrong. 

To Reproduce : https://github.com/xmlking/svelte-starter-kit

### Before SW activation 
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/627951/209621108-8bc74004-004a-42c1-8a8c-d94eda546164.png">

### After SW activation 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/627951/209620823-0e4e84de-10bc-4f6e-b4d9-0204b682503c.png">

### Error in console
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/627951/209620953-c4a8f066-2034-4a22-b26b-1cc27c18e300.png">

**Comment by userquin** [comment]
@xmlking what build are you using? All pages generated without any script, and cannot register sw...

**Comment by xmlking** [comment]
in 
https://github.com/xmlking/svelte-starter-kit

```
pnpm node:build
# this generate ./build
pnpm preview 
```

**Comment by xmlking** [comment]
I created this minimal repo to reproduce the issue https://github.com/xmlking/SPA-aaa-sveltekit-node-vite-pwa-issue

Steps to reproduce 
1. `gh repo clone xmlking/SPA-aaa-sveltekit-node-vite-pwa-issue`
2. `pnpm i`
3. `pnpm build`
4. `pnpm preview`
5.  open `http://localhost:4173/` and wait for `SW Registered` in console 
6. navigate to `HELLO` tab `http://localhost:4173/demo/hello`
7. when you reload this page (browser refresh) you will see layout shifted page and errors in console log

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/627951/209708818-16236b2f-bf3e-49dd-940c-5cdfd92c63ca.png">

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/627951/209709079-1399c18a-dffe-4b5f-869b-0c3b2624b215.png">


Server side errors
```log
Error: Not found: /demo/_app/immutable/assets/_layout-8454f68e.css
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2712:18)
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2599:34)
    at options.hooks.handle (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2829:59)
    at respond (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2597:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Not found: /demo/_app/immutable/assets/ReloadPrompt-8b6f04a5.css
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2712:18)
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2599:34)
    at options.hooks.handle (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2829:59)
    at respond (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2597:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Not found: /demo/_app/immutable/assets/_page-265a38f0.css
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2712:18)
    at resolve (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2599:34)
    at options.hooks.handle (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2829:59)
    at respond (file:///Users/schintha/Developer/Work/SPA/aaa/sveltekit-node-vite-pwa-issue/.svelte-kit/output/server/index.js:2597:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by xmlking** [comment]
for routers in root `http://localhost:4173/` there is no problem as assets are relative to root. 
but this is the only problem for sub routers e.g., `http://localhost:4173/demo/hello` as there are no assets relative to `demo` path
