### ISSUE TITLE
Typescript alias issues 

### ISSUE THREAD

**Issue by arsonik** [vite-pwa/vite-plugin-pwa#529]
Hey !

I am having issue with my worker written in typescript and using aliased imports like that 
`import { xxx } from '@/generated/gql.types';`
Working perfectly during dev running `vite`

But when I try to `vite build` my Vue 3 app its does build the vue part
and then the service worker build end up with this error : `Error: [vite]: Rollup failed to resolve import`
```
[...]
vite v4.3.9 building for production...
✓ 3 modules transformed.
✓ built in 31ms
[vite]: Rollup failed to resolve import "@/generated/gql.types" from "[REDACTED]]/src/states/user.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@/generated/gql.types" from "[REDACTED]]/src/states/user.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file://[REDACTED]]/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
    at onRollupWarning (file://[REDACTED]]/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46621:9)
    at onwarn (file://[REDACTED]]/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
    at Object.onwarn (file://[REDACTED]]/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:25419:13)
    at ModuleLoader.handleInvalidResolvedId (file://[REDACTED]]/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23992:26)
    at file://[REDACTED]]/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23952:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

here is my vite config:
```export default defineConfig({
  resolve: {
    alias: {
      '@': srcPath,
    },
  },
  build: {
    sourcemap: true,
  },
  plugins: [
    vue(),
    VitePWA({
      registerType: 'autoUpdate',
      strategies: 'injectManifest',
      devOptions: {
        enabled: true,
        type: 'module',
        navigateFallback: 'index.html',
      },
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        injectionPoint: undefined,
      },
      injectRegister: 'script',
      manifest: {
        userVisibleOnly: true,
      },
    }),
  ],
});
```

any help please ?

**Comment by userquin** [comment]
@arsonik we need to provide alias entry in custom sw build.

**Comment by arsonik** [comment]
I would love to open a PR and try to fix that!
But I have no idea where to start !

**Comment by userquin** [comment]
Check `src/module.ts`, there is a generate inject manifest function using vite build function

**Comment by arsonik** [comment]
That was easy :)
PR is coming

**Comment by arsonik** [comment]
well now I have a generated sw.js
but I get this error in the browser `Unncaught SyntaxError: Cannot use import statement outside a module (at sw.js:1:1)`
 the content is:
```import { s as f } from "./sw-4e529c8c.mjs";
export {
  f as default
};```

**Comment by arsonik** [comment]
My bad ! 
`rollupFormat: 'iife',`
fixed that for me

**Comment by userquin** [comment]
@arsonik thx, `v0.16.2` released
