### ISSUE TITLE
Vite build error `0.16.4` `Error: Dynamic require of "workbox-build" is not supported`

### ISSUE THREAD

**Issue by mathiash98** [vite-pwa/vite-plugin-pwa#540]
Vite: `4.3.9`
Vue: `3.3.4`
vite-plugin-pwa: `0.16.4`
NodeJs: `20.3.0`

Error:
```
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
error during build:
Error: Dynamic require of "workbox-build" is not supported
    at file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite-plugin-pwa/dist/index.js:6:9
    at loadWorkboxBuild (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite-plugin-pwa/dist/index.js:258:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateServiceWorker (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite-plugin-pwa/dist/index.js:291:26)
    at async _generateSW (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite-plugin-pwa/dist/index.js:459:5)
    at async Object.handler (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite-plugin-pwa/dist/index.js:589:11)
    at async PluginDriver.hookParallel (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24821:17)
    at async Object.close (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:26073:13)
    at async build (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46487:13)
    at async CAC.<anonymous> (file:///Users/mathias/Documents/GitHub/Frontend/node_modules/vite/dist/node/cli.js:812:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Tried:
0.16.x
0.15.x
0.14.x

Potentially related issues:
https://github.com/vite-pwa/vite-plugin-pwa/issues/405
Which @userquin fixed by https://github.com/vite-pwa/vite-plugin-pwa/pull/406

**Comment by userquin** [comment]
From 0.16.0 you need Node 16: https://github.com/vite-pwa/vite-plugin-pwa#-install

**Comment by userquin** [comment]
@mathiash98 can you provide a minimal repro?

**Comment by mathiash98** [comment]
Upon creating the minimal repro I found out I still had `"vue-cli-plugin-vite": "~1.5.0",` installed from when I transitioned from vue-cli-service to Vite.

Removing this package solved the problem!

Thanks for the time @userquin
