### ISSUE TITLE
Adding globPatterns to PWA

### ISSUE THREAD

**Issue by R0N1n-dev** [vite-pwa/vite-plugin-pwa#551]
I used the method used in the Vue-router example
```js
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import lightningcss from 'vite-plugin-lightningcss'
import VueRouter from 'unplugin-vue-router/vite'
import { VitePWA } from 'vite-plugin-pwa'
import replace from '@rollup/plugin-replace'

const pwaOptions = {
  mode: 'development',
  base: '/',
  includeAssets: ['favicon.svg'],
  manifest: {
    name: 'Vue 3 PWA ',
    short_name: 'Vite 3 PWA ',
    theme_color: '#ffffff',
    display: 'standalone',
    background_color: '#ffffff',
    icons: [
      {
        src: 'pwa-192x192.png',
        sizes: '192x192',
        type: 'image/png'
      },
      {
        src: 'pwa-512x512.png',
        sizes: '512x512',
        type: 'image/png'
      },
      {
        src: 'pwa-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any maskable'
      }
    ]
  },
  devOptions: {
    enabled: process.env.SW_DEV === 'true',
    /* when using generateSW the PWA plugin will switch to classic */
    type: 'module',
    navigateFallback: 'index.html',
    suppressWarnings: true
  }
}

const replaceOptions = { __DATE__: new Date().toISOString() }
const claims = process.env.CLAIMS === 'true'
const reload = process.env.RELOAD_SW === 'true'
const selfDestroying = process.env.SW_DESTROY === 'true'

if (process.env.SW === 'true') {
  pwaOptions.srcDir = 'src'
  pwaOptions.filename = claims ? 'claims-sw.js' : 'prompt-sw.js'
  pwaOptions.strategies = 'injectManifest'
  pwaOptions.manifest.name = 'PWA Inject Manifest'
  pwaOptions.manifest.short_name = 'PWA Inject'
  pwaOptions.injectManifest.globPatterns = [
    // all packaged resources are stored here
    'assets/*',
    '*.{svg,png,jpg}',
    '*.html'
  ]
}

if (claims) {
  pwaOptions.registerType = 'autoUpdate'
  pwaOptions.workbox.globPatterns = [
    // all packaged resources are stored here
    'assets/*',
    '*.{svg,png,jpg}',
    '*.html'
  ]
}

if (reload) {
  // @ts-expect-error overrides
  replaceOptions.__RELOAD_SW__ = 'true'
}

if (selfDestroying) pwaOptions.selfDestroying = selfDestroying

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    VueRouter({}),
    vue(),
    VitePWA(pwaOptions),
    replace(replaceOptions),
    Components(),
    lightningcss({
      browserslist: '>= 0.25%'
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

On running the build command for building with the service worker
```js
"run-build-sw": "rimraf dist && DEBUG=vite-plugin-pwa BASE_URL=/ SOURCE_MAP=true SW=true vite build"
```
get the following error:
```js
mozeik@pop-os:~/vue3-vite-pwa$ bun run run-build-sw
$ rimraf dist && DEBUG=vite-plugin-pwa BASE_URL=/ SOURCE_MAP=true SW=true vite build
failed to load config from /home/mozeik/vue3-vite-pwa/vite.config.js
error during build:
TypeError: Cannot set properties of undefined (setting 'globPatterns')
    at Object.<anonymous> (/home/mozeik/vue3-vite-pwa/vite.config.js:87:272)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at _require.extensions.<computed> [as .js] (file:///home/mozeik/vue3-vite-pwa/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:66199:24)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadConfigFromBundledFile (file:///home/mozeik/vue3-vite-pwa/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:66207:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfigFromFile (file:///home/mozeik/vue3-vite-pwa/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:66032:28)
error: script "run-build-sw" exited with code 1 (SIGHUP)
```

How do I add the globPatterns options and build successfully????

**Comment by userquin** [comment]
You are using bun, check how to configure env vars: we are using pnpm with `shell-emulator: true` in `.npmrc`. You can include `cross-env` dependency, check the history of the vue-router package.json file (this is the PR changing cross-env to shell-emulator https://github.com/vite-pwa/vite-plugin-pwa/pull/516).

**Comment by userquin** [comment]
Uhmm, you should initialize workbox in the claims inside the if statement.

**Comment by userquin** [comment]
Also for inject manifest strategy:
`pwaOptions.workbox = {}` and `pwaOptions.injectManifest ={}`
