### ISSUE TITLE
0.18 cannot find the sw entrypoint.

### ISSUE THREAD

**Issue by cpojer** [vite-pwa/vite-plugin-pwa#658]
My `vite-plugin-pwa` config looks like this:

```ts
VitePWA({
    devOptions: {
      enabled: true,
      type: 'module',
    },
    filename: 'sw.js',
    injectRegister: false,
    registerType: 'autoUpdate',
    srcDir: './service-worker',
    strategies: 'injectManifest',
  })
```

After upgrading to 0.18, my frontend build process fails with this error:

```
PWA v0.18.1
Building service-worker/sw.js service worker ("es" format)...
vite v5.1.1 building for production...
transforming...
✓ 3 modules transformed.
rendering chunks...
computing gzip size...
../dist/sw.mjs  0.78 kB │ gzip: 0.49 kB │ map: 3.32 kB
✓ built in 13ms
error during build:
Error: ENOENT: no such file or directory, rename '../dist/sw.mjs' -> '../dist/sw.js'
    at async Object.rename (node:internal/fs/promises:779:10)
    at async buildSW (/node_modules/.pnpm/vite-plugin-pwa@0.18.1_@types+babel__core@7.20.5_vite@5.1.1_workbox-window@7.0.0/node_modules/vite-plugin-pwa/dist/vite-build-KEO6BU2Y.js:22:5)
    at async generateInjectManifest (/node_modules/.pnpm/vite-plugin-pwa@0.18.1_@types+babel__core@7.20.5_vite@5.1.1_workbox-window@7.0.0/node_modules/vite-plugin-pwa/dist/index.js:208:3)
```

I tried to change `filename` to `sw.mjs` and also tried removing the option, but the error is the same/similar. I didn't make any changes to my build except for upgrading from 0.17.5 to 0.18.

**Comment by userquin** [comment]
I need to add a custom sw build using js, it seems a bug, in the meantime fix the pwa plugin version to 0.17.5.

**Comment by userquin** [comment]
Can you share the repo or minimal reproduction ?

**Comment by userquin** [comment]
It is working, can you share project structure?

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/60028d2d-41f8-4151-a1fd-677a4bd4650e)

**Comment by userquin** [comment]
Tested also with latest Vite 5.1.1 in a new repo outside pwa plugin monorepo (with and without type module):

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/0d52d4e1-509a-487c-b499-86382bab58cf)

**Comment by cpojer** [comment]
I took another look and was able to fix my issue. The problem is the default `outDir` here: https://github.com/vite-pwa/vite-plugin-pwa/commit/865fdade29fa35aa7c16b899a58d6200ddbdd4f9#diff-c752aabc6551914f761ca7aa9d30068688d59fa4ec26a568295d4541537d0025R39-R42

I have a monorepo and my Vite config is in a subfolder. I run my build command like this:
```
pnpm vite build --outDir ../dist/frontend -c ./frontend/vite.config.ts ./frontend/
```

This will compiled `/frontend` and put the output into `/dist/frontend` at the root of my monorepo, however `process.cwd()` would be the root of the monorepo, so `../dest/frontend` will refer to a folder outside of the repo. I added `outDir: join(root, 'dist/frontend')` to my Vite PWA config which solved the issue.

`vite-plugin-pwa` should likely stick to the same resolution algorithm for the `outDir` as Vite does, since Vite itself is working correctly.

**Comment by userquin** [comment]
@cpojer I'm going to review the logic, I need to use configured entries here: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/options.ts#L11

**Comment by userquin** [comment]
@cpojer should be fixed with `v0.18.2`: added 2 scripts (to the root package.json) to this monorepo to test your use case
