### ISSUE TITLE
Removes mock service worker

### ISSUE THREAD

**Issue by houtan-rocky** [vite-pwa/vite-plugin-pwa#693]
Issue: when VitePWA is activated, it conflicts with my (MSWJS)[https://mswjs.io/] mock service worker and apparently removes Mock Service Worker from my application.

steps to reproduce:
Install React-App through vite installation
install and configure vite-plugin-pwa:
```typescript
    VitePWA({
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true,
      },
      injectRegister: 'auto',
      manifest: {
        name: 'test-app',
        short_name: 'TA',
        start_url: '',
        display: 'fullscreen',
        theme_color: '#000',
        background_color: '#fff',
        icons: [
          {
            src: 'favicon/android-chrome-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'favicon/android-chrome-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    }),
```

Behaviour:
the vite-pwa extension, when enabled, removes the mock service worker, and the below error is shown in the console:
```js
createStartHandler.ts:57 Uncaught (in promise) Error: [MSW] Failed to locate the Service Worker registration using a custom "findWorker" predicate.

Please ensure that the custom predicate properly locates the Service Worker registration at "/mockServiceWorker.js".
More details: https://mswjs.io/docs/api/setup-worker/start#findworker

    at startWorkerInstance (createStartHandler.ts:57:15)
    at async SetupWorkerApi.start (setupWorker.ts:179:12)
```

Expected:
Extension to not conflict and remove the mock service worker

**Comment by userquin** [comment]
you can try adding an env var when testing, then use it to disable PWA.

**Comment by houtan-rocky** [comment]
@userquin Isn't there a way to not register other SW's?
If you can show me the direction I might be able to help with that.

**Comment by userquin** [comment]
using `generateSW` I guess no, can you provide a minimal reproduction? Maybe I can check what's happening...

**Comment by userquin** [comment]
If you use a custom service worker you can import `mockServiceWorker.js` script, but since you use `generateSW` strategy there is no way to include that script (iirc you can only have one sw).

**Comment by userquin** [comment]
check registering the msw sw in another scope: check last entry here https://stackoverflow.com/questions/77292614/vite-pwa-not-able-to-register-mock-service-worker-in-parallel-with-other-servi

**Comment by userquin** [comment]
For example, using `@vite-pwa/create-pwa` with inject manifest (the `prompt-sw.ts` should be `sw.ts`):

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/de50bddd-c5f5-417e-bb5c-18d328cb4b88)
