### ISSUE TITLE
Letting vite create a manifest.json with the VitePWA plugin enabled will cause `vite build` to fail

### ISSUE THREAD

**Issue by martylukyy** [vite-pwa/vite-plugin-pwa#798]
Hi,

during an upgrade to vite 6 i encountered an issue where `vite build` fails
when letting vite create a manifest.json with the manifest build option while VitePWA is in the plugins array.

```
error during build:
[vite:manifest] Cannot read properties of undefined (reading 'length')
    at Object.generateBundle (file:///home/projects/vitejs-vite-bj1cha/node_modules/vite/dist/node/chunks/dep-C6qYk3zB.js:13637:58)
    at Object.handler (file:///home/projects/vitejs-vite-bj1cha/node_modules/vite/dist/node/chunks/dep-C6qYk3zB.js:50896:15)
    at eval (file:///home/projects/vitejs-vite-bj1cha/node_modules/rollup/dist/es/shared/node-entry.js:20837:40)
    at https://vitejsvitebj1cha-1c10.w-credentialless-staticblitz.com/blitz.88b6dd69.js:40:23076
```

Here is a quick repro for the issue:
https://stackblitz.com/edit/vitejs-vite-bj1cha?file=vite.config.js

Removing VitePWA from the plugin array or not letting vite create a manifest.json will make `vite build` succeed.

Not sure if there is something to be done on your side or if this is an issue upstream at vite.
In case this has to be fixed upstream please leave a quick comment so i can open this issue at vitejs/vite.

This issue is reproducible with v0.21.0 and PR 786.

Kind regards
martyluky

ref #786 
ref #797

**Comment by userquin** [comment]
should be fixed using this version: https://pkg.pr.new/vite-plugin-pwa@8bcc1b7 (check last commit in the PR)

**Comment by userquin** [comment]
closed via #797

**Comment by userquin** [comment]
sorry, this issue is using the environment api PR:

I'm going to release a new minor (v0.22.0) adding vite 6 to the peers + fix build when manifest enabled via https://github.com/vite-pwa/vite-plugin-pwa/pull/797 PR : we're going to keep https://github.com/vite-pwa/vite-plugin-pwa/pull/786 (using Vite 6 Environment API) open for a while, we want to do some more tests.

**Comment by userquin** [comment]
@martylukyy looks like the issue fixed in Vite but not yet released: https://github.com/vitejs/vite/pull/19174

Check https://stackblitz.com/edit/vitejs-vite-jrmcqmbw?file=package.json (with pnpm) using pkg-pr-new from the PR: use `pnpm build`  instead `npm run build`.

**Comment by userquin** [comment]
@martylukyy can you test with Vite 6.0.11?

**Comment by robertmoura** [comment]
@userquin This got fixed for me a few releases ago 😊

**Comment by martylukyy** [comment]
Sorry for the late reply but life happened in the last weeks 😄 
Yes this has been fixed! 

Thank you very much for your effort and apologies for the late reply again!
