### ISSUE TITLE
vite-plugin-pwa fails when vite-plugin-glsl is also used

### ISSUE THREAD

**Issue by eugene-khyst** [vite-pwa/vite-plugin-pwa#804]
vite-plugin-pwa build fails when GLSL (`*.glsl`) files are processed with [vite-plugin-glsl](https://github.com/UstymUkhman/vite-plugin-glsl).

It looks like vite-plugin-pwa tries to treat `*.glsl` files as JS and fails.

But I can't find a way to instruct vite-plugin-pwa to ignore `*.glsl` files. There is no `exclude` or `ignore` configuration properties.

```js
import react from '@vitejs/plugin-react';
import {defineConfig} from 'vite';
import glsl from 'vite-plugin-glsl';
import {VitePWA} from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    glsl({
      compress: true,
    }),
    react(),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'service-worker.ts',
      manifest: false,
      injectRegister: false,
    }),
  ],

  worker: {
    plugins: () => [
      glsl({
        compress: true,
      }),
    ],
  },
});
```

```
x Build failed in 1.66s
error during build:
src/services/image/filter/glsl/color-correction.glsl (1:9): Expected ';', '}' or <eof> (Note that you need plugins to import files that are not JavaScript)
file: /home/evgeniy/projects/artistassistapp/src/services/image/filter/glsl/color-correction.glsl:1:9

1: #version 300 es
            ^
2: 
3: precision mediump float;

    at getRollupError (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
    at ParseError.initialise (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/node-entry.js:13252:28)
    at convertNode (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/node-entry.js:14963:10)
    at convertProgram (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/node-entry.js:14206:12)
    at Module.setSource (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/node-entry.js:15949:24)
    at async ModuleLoader.addModuleSource (file:///home/evgeniy/projects/artistassistapp/node_modules/rollup/dist/es/shared/node-entry.js:19827:13)
```

**Comment by eugene-khyst** [comment]
It turned out that I need to add `glsl` plugin to [injectManifest.buildPlugins.vite](https://vite-pwa-org.netlify.app/guide/inject-manifest.html#custom-rollup-and-vite-plugins):

```js
VitePWA({
  // ...
  injectManifest: {
    buildPlugins: {
      vite: [
        glsl({
          compress: true,
        }),
      ],
    },
  },
}),
```
